name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: main
  pull_request:
    branches: "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install just from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: just
      - name: Install Typst
        uses: typst-community/setup-typst@v4
          with:
            typst-version: 0.12.0
      - name: Run checks
        run: |
          just package local
          just package preview
          just gallery
          # TODO: run unit tests here
